set_property PACKAGE_PIN L14 [get_ports A]
set_property PACKAGE_PIN K16 [get_ports B]
set_property PACKAGE_PIN H15 [get_ports Y]
set_property IOSTANDARD LVCMOS33 [get_ports A]
set_property IOSTANDARD LVCMOS33 [get_ports Y]
set_property IOSTANDARD LVCMOS33 [get_ports B]
