set_property PACKAGE_PIN L14 [get_ports in1]
set_property PACKAGE_PIN K16 [get_ports in2]
set_property PACKAGE_PIN H15 [get_ports out]
set_property PACKAGE_PIN N16 [get_ports sel]
set_property IOSTANDARD LVCMOS33 [get_ports in1]
set_property IOSTANDARD LVCMOS33 [get_ports in2]
set_property IOSTANDARD LVCMOS33 [get_ports out]
set_property IOSTANDARD LVCMOS33 [get_ports sel]
