######################################################################
#
# File name : tb_ip_clk_wiz_compile.do
# Created on: Sat Apr 06 21:50:47 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/work
C:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_2020.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_2020.4\\win64\\vlog  -incr -work xil_defaultlib  "+incdir+../../../../ip_clk_wiz.gen/sources_1/ip/clk_wiz_0" \
"../../../../ip_clk_wiz.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_clk_wiz.v" \
"../../../../ip_clk_wiz.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.v" \
"../../../../ip_clk_wiz.srcs/sources_1/new/ip_clk_wiz.v" \
"../../../../sim/tb/tb_ip_clk_wiz.v" \


# compile glbl module
C:\\modeltech64_2020.4\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

