######################################################################
#
# File name : tb_ip_clk_wiz_wave.do
# Created on: Sat Apr 06 21:50:49 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
